<div class="white-space-50"></div>
<!-- Services -->
<div class="row">
    <div class="col-xs-12 col-sm-12">
        <div class="block-title">
            <h3>What <span>I Do</span></h3>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="col-inner">
            <div class="info-list-w-icon">
                <div class="info-block-w-icon">
                    <div class="ci-icon">
                        <i class="lnr lnr-store"></i>
                    </div>
                    <div class="ci-text">
                        <h4>Motivation Speeches</h4>
                        <p>Pellentesque pellentesque, ipsum sit amet auctor accumsan, odio tortor bibendum massa, sit amet ultricies ex lectus scelerisque nibh. Ut non sodales.</p>
                    </div>
                </div>
                <div class="info-block-w-icon">
                    <div class="ci-icon">
                        <i class="lnr lnr-laptop-phone"></i>
                    </div><div class="ci-text">
                        <h4>Educator</h4>
                        <p>Pellentesque pellentesque, ipsum sit amet auctor accumsan, odio tortor bibendum massa, sit amet ultricies ex lectus scelerisque nibh. Ut non sodales.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6">
        <div class="col-inner">
            <div class="info-list-w-icon">                                                
                <div class="info-block-w-icon">
                    <div class="ci-icon">
                        <i class="lnr lnr-flag"></i>
                    </div><div class="ci-text">
                        <h4>Content Writer</h4>
                        <p>Pellentesque pellentesque, ipsum sit amet auctor accumsan, odio tortor bibendum massa, sit amet ultricies ex lectus scelerisque nibh. Ut non sodales.</p>
                    </div>
                </div>
                <div class="info-block-w-icon">
                    <div class="ci-icon">
                        <i class="lnr lnr-flag"></i>
                    </div><div class="ci-text">
                        <h4>Organising and managing cultural programmes</h4>
                        <p>Pellentesque pellentesque, ipsum sit amet auctor accumsan, odio tortor bibendum massa, sit amet ultricies ex lectus scelerisque nibh. Ut non sodales.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="col-inner">
            <div class="info-list-w-icon">
                <div class="info-block-w-icon">
                    <div class="ci-icon">
                        <i class="lnr lnr-store"></i>
                    </div>
                    <div class="ci-text">
                        <h4>Anchoring</h4>
                        <p>Pellentesque pellentesque, ipsum sit amet auctor accumsan, odio tortor bibendum massa, sit amet ultricies ex lectus scelerisque nibh. Ut non sodales.</p>
                    </div>
                </div>
                <div class="info-block-w-icon">
                    <div class="ci-icon">
                        <i class="lnr lnr-laptop-phone"></i>
                    </div><div class="ci-text">
                        <h4>Dancing</h4>
                        <p>Pellentesque pellentesque, ipsum sit amet auctor accumsan, odio tortor bibendum massa, sit amet ultricies ex lectus scelerisque nibh. Ut non sodales.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6">
        <div class="col-inner">
            <div class="info-list-w-icon">
                <div class="info-block-w-icon">
                    <div class="ci-icon">
                        <i class="lnr lnr-pencil"></i>
                    </div>
                    <div class="ci-text">
                        <h4>Art work</h4>
                        <p>Pellentesque pellentesque, ipsum sit amet auctor accumsan, odio tortor bibendum massa, sit amet ultricies ex lectus scelerisque nibh. Ut non sodales.</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>