<!-- Home Subpage -->
<section data-id="home" class="animated-section start-page">
    <div class="section-content vcentered">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="title-block">
                    <div class="header-photo d-xl-none d-sm-block">
                        <?php
                        do_action("logo", "logo", "", "Maryam Mirza");
                        ?>
                    </div>
                    <h2><?php echo get_field('title', 'option'); ?></h2>
                    <div class="owl-carousel text-rotation">                                    
                        <div class="item">
                            <div class="sp-subtitle">Explorer | Educator</div>
                        </div>

                        <div class="item">
                            <div class="sp-subtitle">Motivational Speaker</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>