<section data-id="contact" class="animated-section">
    <div class="page-title">
        <h2>Contact</h2>
    </div>

    <div class="section-content">

        <div class="row">
            <!-- Contact Info -->
            <div class="col-xs-12 col-sm-4">
                <div class="lm-info-block gray-default">
                    <i class="lnr lnr-map-marker"></i>
                    <h4><?php echo get_field('location', 'option'); ?></h4>
                    <span class="lm-info-block-value"></span>
                    <span class="lm-info-block-text"></span>
                </div>

                <div class="lm-info-block gray-default">
                    <i class="lnr lnr-phone-handset"></i>
                    <h4><?php echo get_field('phone', 'option'); ?></h4>
                    <span class="lm-info-block-value"></span>
                    <span class="lm-info-block-text"></span>
                </div>

                <div class="lm-info-block gray-default">
                    <i class="lnr lnr-envelope"></i>
                    <h4>
                        <a href="#" class="__cf_email__" ><?php echo get_field('email   ', 'option'); ?></a>
                    </h4>
                    <span class="lm-info-block-value"></span>
                    <span class="lm-info-block-text"></span>
                </div>

                <div class="lm-info-block gray-default">
                    <i class="lnr lnr-checkmark-circle"></i>
                    <h4><?php echo get_field('freelance_available   ', 'option'); ?></h4>
                    <span class="lm-info-block-value"></span>
                    <span class="lm-info-block-text"></span>
                </div>


            </div>
            <!-- End of Contact Info -->

            <!-- Contact Form -->
            <div class="col-xs-12 col-sm-8">
                <div id="map" class="map">
                    <div class="lmpixels-map">
                        
                        <?php echo html_entity_decode(get_field('location_frame   ', 'option')); ?>

                    </div>
                </div>
                <div class="block-title">
                    <h3>How Can I <span>Help You?</span></h3>
                </div>
                <?php
                echo do_shortcode('[gravityform id="1" title="true" description="true" ajax="true"]');
                ?>
                
            </div>
            <!-- End of Contact Form -->
        </div>

    </div>
</section>