<div class="content-area">
    <div class="single-page-content">
        <div class="page-title">
            <h2>Blog</h2>
        </div>

        <div class="section-content">
            <div class="row">
                <div class="col-xs-12 col-sm-12">
                    <div class="blog-masonry two-columns clearfix">

                        <?php
                        foreach ($this->data as $value) {
                            ?>

                            <div class="item post-1">
                                <div class="blog-card">
                                    <div class="media-block">
                                        <div class="category">
                                            <?php echo the_category('', '', $value->ID); ?>
                                        </div>
                                        <a href="<?php echo get_permalink($value->ID); ?>">                                        
                                            <img src="<?php echo get_the_post_thumbnail_url($value->ID); ?>" class="size-blog-masonry-image-two-c" alt="Why I Switched to Sketch For UI Design" title="" />
                                            <div class="mask"></div>
                                        </a>
                                    </div>
                                    <div class="post-info">
                                        <div class="post-date"><?php echo date("D-m-y", strtotime($value->post_date)); ?></div>
                                        <a href="<?php echo get_permalink($value->ID); ?>">
                                            <h4 class="blog-item-title"><?php echo $value->post_title; ?></h4>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                        <!-- Blog Post 1 -->

                    </div>
                </div>
            </div>
        </div>



    </div>
</div>