<section data-id="blog" class="animated-section">
    <div class="page-title">
        <h2>Blog</h2>
    </div>
    <div class="section-content">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="blog-masonry two-columns clearfix">
                    <?php
                    query_posts('post_type=post&posts_per_page=4');
                    if (have_posts()) :
                        while (have_posts()) : the_post();
                            // Your loop code
                            get_template_part('template-parts/content', 'list');
                        endwhile;
                        ?>
                        <div class="col-md-12 center-block" style="text-align: center;"> 
                            <a href="<?php echo esc_url(home_url('/blog'));?>" class="btn btn-primary center-block">All Blog</a>
                        </div>
                        <!-- End of the main loop -->                                                
                        <?php
                    else :
                        ?>
                        <div class="col-xs-12 col-sm-12">
                            <?php esc_html_e('Sorry, no posts were found.', 'WonderMirza'); ?>                        
                        </div>
                        <div class="col-xs-12 col-sm-12">
                            <?php get_search_form(); ?>
                        </div>
                    <?php
                    endif;
                    ?>
                </div>
            </div>
        </div>
    </div>


</section>